### PR TITLE
(GH-1724) Fix bug in remote transport from nil results

### LINKED ISSUE #1724: Bolt throws exception if target returns "null" on a remote task
## Describe the Bug
When running a plan that calls `run_task()` on a `remote` task, then the task itself returns `null`, then Bolt throws an exception when trying to print out the results:

Example target result:
```
{"target":"hostname.domain.tld","action":null,"object":null,"status":"success","value":{"_output":""}}
```

```
Traceback (most recent call last):
        11: from /opt/puppetlabs/bolt/bin/bolt:23:in `<main>'
        10: from /opt/puppetlabs/bolt/bin/bolt:23:in `load'
         9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/exe/bolt:10:in `<top (required)>'
         8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/cli.rb:373:in `execute'
         7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/cli.rb:524:in `run_plan'
         6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:355:in `print_plan_result'
         5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:362:in `print_result_set'
         4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `each'
         3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `each'
         2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `block in each'
         1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:362:in `block in print_result_set'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:101:in `print_result': undefined method `capitalize' for nil:NilClass (NoMethodError)
```

If i run the task itself, it does not error.

## Expected Behavior
No exception is thrown when running from a plan.

## Steps to Reproduce
tasks/plan_exception.rb
```ruby
#!/usr/bin/env ruby
require_relative '../../ruby_task_helper/files/task_helper.rb'

# Bolt task for enabling/disabling monitoring alerts in SolarWinds
class PlanExceptionTask < TaskHelper
  def task(**kwargs)
    nil
  end
end

PlanExceptionTask.run if $PROGRAM_NAME == __FILE__
```

tasks/plan_exception.json
```json
{
  "description": "Returns null",
  "remote": true,
  "files": [
    "ruby_task_helper/files/task_helper.rb"
  ],
  "parameters": {}
}
```

plans/plan_exception.pp
```
plan mymodule::plan_exception () {
  return(run_task('mymodule::plan_exception', 'remote_target'))
}
```

inventory.yaml
```
---
version: 2
groups:
  - name: remote_target
    config:
      transport: remote
      remote: {}
    targets:
      - hostname.domain.tld
```

Run the plan on the CLI
```
$ bolt plan run mymodule::plan_exception --targets remote_target
Starting: plan mymodule::plan_exception
Starting: plan mymodule::plan_exception
Starting: task mymodule::plan_exception on hostname.domain.tld
Finished: task mymodule::plan_exception with 0 failures in 0.09 sec
Finished: plan mymodule::plan_exception in 0.1 sec
Finished: plan mymodule::plan_exception in 0.1 sec
Finished on hostname.domain.tld:
Traceback (most recent call last):
        11: from /opt/puppetlabs/bolt/bin/bolt:23:in `<main>'
        10: from /opt/puppetlabs/bolt/bin/bolt:23:in `load'
         9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/exe/bolt:10:in `<top (required)>'
         8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/cli.rb:373:in `execute'
         7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/cli.rb:524:in `run_plan'
         6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:355:in `print_plan_result'
         5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:362:in `print_result_set'
         4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `each'
         3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `each'
         2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/result_set.rb:41:in `block in each'
         1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:362:in `block in print_result_set'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.3.0/lib/bolt/outputter/human.rb:101:in `print_result': undefined method `capitalize' for nil:NilClass (NoMethodError)
```

## Environment
 - Version: `2.3.0`
 - Platform: `CentOS 7`

### PR DESCRIPTION
**Pull request by nmaludy**
Closes #1724, #1718 

Seems that sometimes Results are created without actions, causing exceptions to be thrown when referenced from the Human outputter.

**TODO**
- Should i put a guard in the human outputter to check for `nil` actions? https://github.com/puppetlabs/bolt/blob/master/lib/bolt/outputter/human.rb#L101
- Need to add tests for the `remote` transport. There doesn't seem to be any. I'm thinking the easiest course of action would be to write some unit tests that mock out the executor.  **Does this sound right?**
- Integration tests i could probably write based off of the `local` transport. **Does this sound right?**

### CODE REVIEW

File: lib/bolt/executor.rb [hunk 1]
```diff
@@ -302,11 +302,11 @@ def wait_until_available(targets,
         batch_execute(targets) do |transport, batch|
           with_node_logging('Waiting until available', batch) do
             wait_until(wait_time, retry_interval) { transport.batch_connected?(batch) }
-            batch.map { |target| Result.new(target) }
+            batch.map { |target| Result.new(target, action: 'wait_util_available', object: description) }
           rescue TimeoutError => e
             available, unavailable = batch.partition { |target| transport.batch_connected?([target]) }
             (
-              available.map { |target| Result.new(target) } +
+              available.map { |target| Result.new(action: 'wait_util_available', object: description) } +
```
Comment (donoghuc) [inline lib/bolt/executor.rb:309]: I had a test for this in https://github.com/puppetlabs/bolt/pull/1719/commits/ca6de28c7252dc9bd29fbbe5ac29dc143c25787c

File: lib/bolt/transport/remote.rb [hunk 2]
```diff
@@ -34,7 +34,7 @@ def run_task(target, task, arguments, options = {})
         remote_task = task.remote_instance
 
         result = transport.run_task(proxy_target, remote_task, arguments, options)
```
Comment (donoghuc) [inline lib/bolt/transport/remote.rb:36]: Wont the transports already give a Result object? Why do we construct a new one?

File: lib/bolt/executor.rb (hunk 1 above)
Comment (nmaludy) [reply lib/bolt/executor.rb:309]: Seems like your fix is more extensive than mine, want to pull my change in for the remote transport into taht as well? Or do you want me to just fix the remote stuff and you fix the `wait_until_available` ones?

File: lib/bolt/transport/remote.rb (hunk 2 above)
Comment (nmaludy) [reply lib/bolt/transport/remote.rb:36]: The result is the result from the proxy, rather than the specified target.

It looks like we're creating a new `Result` so that it has the right target specified.

File: lib/bolt/executor.rb (hunk 1 above)
Comment (donoghuc) [reply lib/bolt/executor.rb:309]: I'm not even sure if @puppetlabs/bolt team has had a chance to look at this. I would defer to them as I'm actually working on different team at Puppet now. This was just a bug I hit when working on a different thing.

**Comment by nicklewis** [comment]
Broadly speaking, we need to establish concretely whether all Result objects should have an action or not. If so, then Result should do something to ensure one is present (either make it a required field or have a default). If not, then the human outputter should be updated to accommodate a Result without an action.

File: lib/bolt/transport/remote.rb [hunk 3]
```diff
@@ -34,7 +34,7 @@ def run_task(target, task, arguments, options = {})
...
-        Bolt::Result.new(target, value: result.value)
+        Bolt::Result.new(target, value: result.value, action: 'task', object: task.name)
```
Comment (adreyer) [inline lib/bolt/transport/remote.rb:37]: This part seems obviously correct

**Comment by nmaludy** [comment]
@nicklewis made the requested updates :)

File: lib/bolt/result.rb [hunk 4]
```diff
@@ -19,7 +19,7 @@ def self.from_exception(target, exception)
         }
         error['details']['stack_trace'] = exception.backtrace.join('\n') if exception.backtrace
       end
-      Result.new(target, error: error)
+      Result.new(target, error: error, action: action)
```
Comment (lucywyman) [inline lib/bolt/result.rb:22]:
```suggestion
      Result.new(target, error: error, action: 'action')
```

File: lib/bolt/transport/base.rb [hunk 5]
```diff
@@ -46,13 +46,13 @@ def initialize
         @logger = Logging.logger[self]
       end
 
-      def with_events(target, callback)
+      def with_events(target, callback, action)
```
Comment (lucywyman) [inline lib/bolt/transport/base.rb:49]: Should this be optional, or default to 'action' as well?

Comment (nicklewis) [reply lib/bolt/transport/base.rb:49]: This is only used within Bolt, so we should always have a defined action.ag

File: spec/bolt/result_spec.rb [hunk 6]
```diff
@@ -8,6 +8,33 @@
...
+
+    it 'sets error' do
+      result = Bolt::Result.new(target, error: { 'This' => 'is an error' })
+      expect(result.error_hash).to eq('This' => 'is an error')
+      expect(result.value['_error']).to eq('This' => 'is an error')
+    end
+
+    it 'errors if error is not a hash' do
+      expect { Bolt::Result.new(target, error: 'This is an error') }
+        .to raise_error(RuntimeError, 'TODO: how did we get a string error')
```
Comment (lucywyman) [inline spec/bolt/result_spec.rb:28]: Oh my gosh ha thanks for adding this! Finally testing it after 2 years https://github.com/puppetlabs/bolt/blame/44fbef4d2279298167745b3e3d92be323b9769e1/lib/bolt/result.rb#L99
