### PR TITLE
(GH-1650) Handle exit codes greater than 1 in winrm transport

### LINKED ISSUE #1650: Error with bolt when running Concat module against windows machines
The IAC team have recently been seeing an error appear whenever we apply certain manifests on a windows machine via Bolt. Originally we felt that this may be originating from a puppet agent change however we now feel that it is likely originating from bolt, more information on the investigations into Puppet Agent can be found in [https://tickets.puppetlabs.com/browse/PA-3065|https://cdn1.evernote.com/ion/dist/ce/].
 
The IAC Team have made multiple applications of a select manifest against the windows machines using bolt via litmus, bolt directly and through logging onto the machine and applying it manually. When applying the manifest via bolt in either way the result is an exit code of 1, while applying it manually gives an exit code of 0. I have attached screenshots of the results of each run onto this
 ticket and will paste the output below:
  
 When run locally
```
Administrator@wooden-debacle /cygdrive/c/tmp
$ '../Program Files/Puppet Labs/Puppet/bin/puppet.bat' apply /tmp/manifest_20200129_56833_19lr8ku.pp --detailed-exitcodes
Notice: Compiled catalog for wooden-debacle.delivery.puppetlabs.net in environment production in 0.11 seconds
Error: /Stage[main]/Main/Concat[c:/concat_test/file]/Concat_file[c:/concat_test/file]: Failed to generate additional resources using 'eval_generate': Duplicate key 'one' found with values 'foo' and bar'. Use 'force' attribute to merge keys.
Notice: Applied catalog in 0.02 secondsAdministrator@wooden-debacle /cygdrive/c/tmp
$  echo $?
0
```
When run via litmus
```
  1) force merge of file when run should not force applies manifest twice with stderr check
     On host `wooden-debacle.delivery.puppetlabs.net'
     Failure/Error: expect(apply_manifest(pp, catch_failures: true).stderr).to match("Duplicate key 'one' found with values 'foo' and bar'. Use 'force' attribute to merge keys.")
     RuntimeError:
       apply manifest failed
       ` puppet apply /tmp/manifest_20200129_56833_cptso6.pp --detailed-exitcodes`
       with exit code 1 (expected: [0, 2])
       ====== Start output of failed Puppet apply ======
       puppet.bat : Error: /Stage[main]/Main/Concat[c:/concat_test/file]/Concat_file[c:/concat_test/file]: Failed to generate additional resources using 'eval_generate': Duplicate key 'one' found with values 'foo' and bar'. Use 'force' attribute to merge keys.
           + CategoryInfo          : NotSpecified: (Error: /...merge keys.:String) [], RemoteException
           + FullyQualifiedErrorId : NativeCommandError
       Notice: Compiled catalog for wooden-debacle.delivery.puppetlabs.net in environment production in 0.10 seconds
       Notice: Applied catalog in 0.02 seconds       ====== End output of failed Puppet apply ======     # ./.bundle/gems/ruby/2.5.0/gems/puppet_litmus-0.14.0/lib/puppet_litmus/puppet_helpers.rb:278:in `report_puppet_apply_error'
     # ./.bundle/gems/ruby/2.5.0/gems/puppet_litmus-0.14.0/lib/puppet_litmus/puppet_helpers.rb:79:in `apply_manifest'
     # ./spec/acceptance/force_spec.rb:29:in `block (3 levels) in <top (required)>'
```

 When run via bolt
```
➜  puppetlabs-concat git:(master) ✗ bundle exec bolt command run "puppet apply /tmp/manifest_20200129_56833_19lr8ku.pp --detailed-exitcodes" --targets 'wooden-debacle.delivery.puppetlabs.net' --transport winrm --user Administrator --password Qu@lity! --no-ssl-verify
Deprecation Warning: Starting with Bolt 2.0, inventory file v1 will no longer
be supported. v1 inventory files can be automatically migrated to v2 using
'bolt project migrate'. Inventory files are modified in place and will not
preserve formatting or comments.CLI arguments ["user", "password", "ssl-verify", "transport"] may be overridden by Inventory: /Users/david.swan/.puppetlabs/bolt/inventory.yaml
Started on wooden-debacle.delivery.puppetlabs.net...
Failed on wooden-debacle.delivery.puppetlabs.net:
  The command failed with exit code 1
  STDOUT:
    Notice: Compiled catalog for wooden-debacle.delivery.puppetlabs.net in environment production in 0.11 seconds
    Notice: Applied catalog in 0.02 seconds
  STDERR:
    puppet.bat : Error: /Stage[main]/Main/Concat[c:/concat_test/file]/Concat_file[c:/concat_test/file]: Failed to generate additional resources using 'eval_generate': Duplicate key 'one' found with values 'foo' and bar'. Use 'force' attribute to merge keys.
        + CategoryInfo          : NotSpecified: (Error: /...merge keys.:String) [], RemoteException
        + FullyQualifiedErrorId : NativeCommandError
Failed on 1 target: wooden-debacle.delivery.puppetlabs.net
Ran on 1 target in 8.44 sec
```

 This error originally presented on the concat module, and the results shown above are from the application of the first manifest in the concat modules `force_spec.rb` file.

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

### PR DESCRIPTION
**Pull request by jpogran**
When using `powershell.exe -Command`, PowerShell sets the exit code of `powershell.exe` based on the `success status` of the **last statement**  executed in the command string.

- If the **last statement** is a PowerShell command (think cmdlet/function/etc) success is determined from `$?` which is `0` if `$true` or `1` if `$false`.
- If the **last statement** executed is an external program (not PowerShell code), `1` is returned if the exit code is anything but `0`. This means an exit code of `42` is still a `1` at the end of the execution.
- This does not happen with PowerShell scripts executed with `-File` command and that use a `exit <NUMBER>` to return a success status.

When executing `bolt command run 'foo'`, we are effectively doing a `powershell.exe -Command 'foo'`. This means the exit codes are mapped to `0` and `1` as in the first bullet point. We can pass the 'true' exit code by appending the `exit $LASTEXITCODE` statement to the end of every command. This was applied in f0fe7cdb2258d100940069377050a81aa2d919da, but only for the `local` transport. This fix applies it to the `winrm` transport as well.

This has the side effect of correctly passing the exit code for binary executions, like in the spec test executing `cmd.exe /c exit 42`. The spec test relied on the original (undesired) behavior and marked it passing even though it was the undesired behavior, making the user handle returning the correct exit code using `$LASTEXITCODE`. Since we are now deciding to try to pass the correct `$LASTEXITCODE` in both local and winrm transports, this test is corrected to expect the correct exit code.

Closes #1650

### CODE REVIEW

**Comment by jpogran** [comment]
@puppetlabs/bolt This is potentially a breaking change, in that it passes 'correct' exit codes when before it just emitted a 0 or 1. I suggest we have a diverse set of people test this in different modules/use cases.

**Comment by lucywyman** [comment]
To me, while this is technically a breaking change I don't think it warrants waiting until 3.x to release it. I assume most users check whether the output is nonzero, not explicitly whether it's 1. This seems more like a bugfix to behave the way one would expect than a new feature that would break user workflows.

File: spec/integration/transport/winrm_spec.rb [hunk 1]
```diff
@@ -1032,7 +1032,7 @@ def stub_winrm_to_raise(klass, message)
 
           with_tempfile_containing('script-test-winrm', contents, '.ps1') do |file|
             result = winrm.run_script(target, file.path, [])
-            expect(result).to be_success
+            expect(result).to_not be_success
```
Comment (lucywyman) [inline spec/integration/transport/winrm_spec.rb:1035]: Could we also add a test that this now behaves as expected?

Comment (beechtom) [reply spec/integration/transport/winrm_spec.rb:1035]: `not_to`*

**Review by beechtom — APPROVED** [review]
Lgtm aside from Lucy's unaddressed comment: https://github.com/puppetlabs/bolt/pull/2196/files#r497112520

File: spec/integration/transport/winrm_spec.rb (hunk 1 above)
Comment (lucywyman) [reply spec/integration/transport/winrm_spec.rb:1035]: Still interested in adding a test for the correct behavior

**Review by sanfrancrisko — APPROVED** [review]
LGTM 👍 

I (or someone on the IAC Team) will try to test this with the `puppetlabs-concat` module a.s.a.p. which is where we were originally seeing the issue.

File: spec/integration/transport/winrm_spec.rb (hunk 1 above)
Comment (jpogran) [reply spec/integration/transport/winrm_spec.rb:1056]: Apologies for the delay in response, other work got in the way.

In reviewing the code again and this test, I added more detail in a comment in the affected test to explain to future people who read the code.

As requested, I added another test that ensures it returns 0 and succeeds.

Comment (jpogran) [reply spec/integration/transport/winrm_spec.rb:1056]: I'm working with the IAC team who will validate my changes and ensure they are working

**Comment by adrianiurca** [comment]
Hi all,
I test the concat module with bolt(including this PR) and I can fully confirm that this PR solves our problem. Tests on windows platforms pass and tests on Linux platforms pass also.
Please check the results:
appveyor: https://ci.appveyor.com/project/puppetlabs/puppetlabs-concat/builds/36151980
travis: https://travis-ci.org/github/puppetlabs/puppetlabs-concat/builds/741615148

kind regards,
@adrianiurca

**Comment by adrianiurca** [comment]
Closes: #2318
