### PR TITLE
reintroduce gss-api auth which was removed by 59d3f66

### LINKED ISSUE #1529: gssapi fails on debian buster
## failure to use gssapi authentication

GSSAPI auth doesn't seem to work:

```
Authentication method 'gssapi-with-mic' (Kerberos) is not available.
```

## Expected Behavior

bolt should support all ssh auth methods

## Steps to Reproduce

1. configure ssh config for using gssapi
2. run any bolt command on host

## Environment
 - Version 1.44.0-1buster
 - Platform Debian Buster

## Full stacktrace

```
<Gem::ConflictError> Unable to activate net-ssh-krb-0.4.0, because gssapi-1.3.0 conflicts with gssapi (~> 1.2.0)
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:217:in `try_activate'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/transport/ssh.rb:65:in `initialize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:35:in `new'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:35:in `block (2 levels) in initialize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/delay.rb:87:in `block in value'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/delay.rb:83:in `value'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/delay.rb:137:in `wait'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/concern/obligation.rb:87:in `wait!'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:57:in `transport'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:90:in `block in queue_execute'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:89:in `each'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:89:in `flat_map'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:89:in `queue_execute'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:145:in `batch_execute'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:259:in `block in run_task'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:153:in `log_action'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:255:in `run_task'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/bolt-modules/boltlib/lib/puppet/functions/run_task.rb:127:in `run_task_with_description'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/dispatch.rb:60:in `invoke'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/dispatcher.rb:43:in `block in dispatch'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/dispatcher.rb:42:in `catch'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/dispatcher.rb:42:in `dispatch'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/function.rb:46:in `block in call'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/function.rb:45:in `catch'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/functions/function.rb:45:in `call'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/evaluator/runtime3_support.rb:283:in `block in external_call_function'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/util/profiler.rb:51:in `profile'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pops/evaluator/runtime3_support.rb:282:in `external_call_function'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/compiler.rb:29:in `call_function'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:427:in `block in run_task'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:199:in `block (2 levels) in in_task_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:142:in `block (3 levels) in in_bolt_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:141:in `block (2 levels) in in_bolt_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:468:in `block (3 levels) in main'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/parser/script_compiler.rb:47:in `block in compile'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/parser/script_compiler.rb:42:in `compile'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:465:in `block (2 levels) in main'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:464:in `block in main'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:418:in `main'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:92:in `with_script_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:137:in `block in in_bolt_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:330:in `block in in_environment_context'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:322:in `in_environment_context'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/pal/pal_impl.rb:224:in `in_tmp_environment'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:136:in `in_bolt_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:198:in `block in in_task_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet/context.rb:62:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.11.0/lib/puppet.rb:274:in `override'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:180:in `with_bolt_executor'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:197:in `in_task_compiler'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/pal.rb:425:in `run_task'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/cli.rb:416:in `block in execute'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/cli.rb:402:in `execute'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/exe/bolt:10:in `<top (required)>'
        /opt/puppetlabs/bolt/bin/bolt:23:in `load'
        /opt/puppetlabs/bolt/bin/bolt:23:in `<main>'
        --- Caused by ---
        <Gem::ConflictError> Unable to activate net-ssh-krb-0.4.0, because gssapi-1.3.0 conflicts with gssapi (~> 1.2.0)
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems.rb:218:in `try_activate'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/transport/ssh.rb:65:in `initialize'
        --- Caused by ---
        <LoadError> cannot load such file -- net/ssh/krb
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        /opt/puppetlabs/bolt/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/transport/ssh.rb:65:in `initialize'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:35:in `new'
        /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.44.0/lib/bolt/executor.rb:35:in `block (2 levels) in initialize'
```

### PR DESCRIPTION
**Pull request by faxm0dem**
Fixes #1529

### CODE REVIEW

File: lib/bolt/transport/ssh.rb [hunk 1]
```diff
@@ -102,6 +102,11 @@ def initialize
 
         require 'net/ssh'
         require 'net/scp'
+        begin
+          require 'net/ssh/krb'
```
Comment (donoghuc) [inline lib/bolt/transport/ssh.rb]: We just need the `require 'net/ssh/krb'. Before, when we were not shipping the kerberos gem we would *only* require that library when a user manually installed the gem on their system. Now we have added the kerberos gem to the gemspec and started shipping it in the system packages we build and therefore it will always be available. So we do not need to rescue the `LoadError` anymore. That is what https://github.com/puppetlabs/bolt/pull/1586#pullrequestreview-354130026 was meant to address.

Comment (faxm0dem) [reply lib/bolt/transport/ssh.rb]: ack

**Comment by donoghuc** [comment]
Maybe we need to install that dll on our test runner? (`gssapi32.dll`) We used to ship this gem on windows platforms, so I'm assuming it should work on windows. There are some other gems we do not ship on windows bc of the way we build ruby https://tickets.puppetlabs.com/browse/BOLT-1296 https://github.com/puppetlabs/puppet-runtime/blob/1c36c7d2d3444d1ccd328b087326c262ef2c078b/configs/projects/bolt-runtime.rb#L118-L123

**Comment by donoghuc** [comment]
So apparently the net-ssh-krb gem *only* works with the MIT Kerberos package (and not the built in windows API). So I think we *do* need to rescue the `LoadError`. We can ticket supporting non-MIT Kerberos on windows bolt-controllers for kerberos of netssh. Sorry for the churn!

**Comment by lucywyman** [comment]
I'm reasonably certain we don't need to require the gem - It basically just adds support for a different authentication method to `net/ssh`, which when you have it configured gets called https://github.com/cbeer/net-ssh-kerberos. Our test infrastructure seems to be having network issues so I'm having some trouble verifying, but I recall getting this working without requiring the gem in Bolt.

In order to have `net/ssh` load the config option to use gssapi-with-mic I believe you need to set `PreferredAuthentications gssapi-with-mic` in your SSH config, in addition to the usual `GSSAPIAuthentication yes`.

**Comment by faxm0dem** [comment]
I'm sorry but that's not enough. bolt even helpfully states it's using `gss-api-with-mic` but then it fails. Simply adding the line makes it work.

**Comment by lucywyman** [comment]
Ok, if it's only working for you with the change I don't see any harm in it.

File: lib/bolt/transport/ssh.rb [hunk 2]
```diff
@@ -102,6 +102,7 @@ def initialize
 
         require 'net/ssh'
         require 'net/scp'
```
Comment (lucywyman) [inline lib/bolt/transport/ssh.rb]:
```suggestion
        begin
          require 'net/ssh/krb'
        rescue LoadError
          logger.debug("Authentication method 'gssapi-with-mic' (Kerberos) is not available.")
        end
```

Comment (lucywyman) [reply lib/bolt/transport/ssh.rb]: I opted not to have a more specific message here, because we'd be assuming the cause of the load error. There may be other issues than just running on Windows that cause a loaderror.

Comment (donoghuc) [reply lib/bolt/transport/ssh.rb]: Would committing this suggestion as is delete `require 'net/scp'`?

**Comment by lucywyman** [comment]
Thanks so much for this @faxm0dem!!

**Comment by faxm0dem** [comment]
thanks so much to you for being so helpful, kind and reactive!
