### PR TITLE
(GH-2197) Error gracefully when yaml plans fail to parse

### LINKED ISSUE #2197: Unhelpful error message when yaml plan fails to parse
## Describe the Bug
The following YAML plan has an extra space before the resources hash and when attempting to run causes a stack trace.  

```
NoWay:myboltproj nw$ cat plans/prometheus.yaml
# This is the structure of a simple plan. To learn more about writing
# YAML plans, see the documentation: http://pup.pt/bolt-yaml-plans

# The description sets the description of the plan that will appear
# in 'bolt plan show' output.
description: A plan created with bolt plan new

# The parameters key defines the parameters that can be passed to
# the plan.
parameters:
  targets:
    type: TargetSpec
    description: A list of targets to run actions on
    default: localhost

# The steps key defines the actions the plan will take in order.
steps:
 - resources:
    - class: prometheus
    targets: $targets
    description: 'Install prometheus'
NoWay:myboltproj nw$ /opt/puppetlabs/bin/bolt plan run myboltproj::prometheus --targets="agent-no-pe-centos"
undefined method `pos' for #<Psych::SyntaxError:0x00007fdf8b32b258> on node noway.vpn.puppet.net
Traceback (most recent call last):
	32: from /opt/puppetlabs/bolt/bin/bolt:23:in `<main>'
	31: from /opt/puppetlabs/bolt/bin/bolt:23:in `load'
	30: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.27.0/exe/bolt:11:in `<top (required)>'
	29: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.27.0/lib/bolt/cli.rb:449:in `execute'
	28: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.27.0/lib/bolt/cli.rb:697:in `run_plan'
	27: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.27.0/lib/bolt/pal.rb:352:in `get_plan_info'
	26: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.27.0/lib/bolt/pal.rb:163:in `in_bolt_compiler'
	25: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/pal/pal_impl.rb:231:in `in_tmp_environment'
	24: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/pal/pal_impl.rb:329:in `in_environment_context'
	23: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet.rb:314:in `override'
	22: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/context.rb:62:in `override'
	21: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/pal/pal_impl.rb:337:in `block in in_environment_context'
	20: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.27.0/lib/bolt/pal.rb:165:in `block in in_bolt_compiler'
	19: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet.rb:314:in `override'
	18: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/context.rb:62:in `override'
	17: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.27.0/lib/bolt/pal.rb:171:in `block (2 levels) in in_bolt_compiler'
	16: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/pal/pal_impl.rb:96:in `with_script_compiler'
	15: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/pal/pal_impl.rb:431:in `main'
	14: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet.rb:314:in `override'
	13: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/context.rb:62:in `override'
	12: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/pal/pal_impl.rb:464:in `block in main'
	11: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet.rb:314:in `override'
	10: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/context.rb:62:in `override'
	 9: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/pal/pal_impl.rb:465:in `block (2 levels) in main'
	 8: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/parser/script_compiler.rb:42:in `compile'
	 7: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet.rb:314:in `override'
	 6: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/context.rb:62:in `override'
	 5: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/parser/script_compiler.rb:47:in `block in compile'
	 4: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/puppet-6.18.0/lib/puppet/pal/pal_impl.rb:472:in `block (3 levels) in main'
	 3: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.27.0/lib/bolt/pal.rb:174:in `block (3 levels) in in_bolt_compiler'
	 2: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.27.0/lib/bolt/pal.rb:196:in `rescue in block (3 levels) in in_bolt_compiler'
	 1: from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.27.0/lib/bolt/pal.rb:22:in `from_preformatted_error'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-2.27.0/lib/bolt/pal.rb:35:in `from_error': undefined method `pos' for #<Psych::SyntaxError:0x00007fdf8b32b258> on node noway.vpn.puppet.net (Puppet::Error)
```

## Expected Behavior
Ideally an error pointing to a line number that has the parsing issue.  Short of that just an error indicating what had an issue parsing.  

I assumed I had mis-formatted my inventory.yaml file when I saw the error but running `bolt inventory show` proved to me that it wasn't an inventory.yaml issue.  

## Environment
 - Version 2.27.0 
 - Platform Mac os

### PR DESCRIPTION
**Pull request by lucywyman**
Previously when raising an error from a plan run in Bolt we would only
check if the error had a `file` method and use that to determine whether
the error was from Puppet or not. If the error was from Puppet we could
assume other methods on the error, like line and pos. However,
when yaml plans were syntactically invalid and failed to parse this
would raise a Psych::SyntaxError, which has a `file` method but not a
`pos` method. This would cause a stacktrace when we assumed the error
was a Puppet error and tried to call `pos` on it.

This change modifies the details hash to only add each key if the
corresponding method exists on the error. We can't be sure this will
catch all relevant details from an error (for example if the `pos`
exists on an error but is accessed by a method `position`), but it will
at least not stacktrace when a non-Puppet error with any of those
methods is raised.

Closes #2197

!bug

* **Invalid YAML plans now fail gracefully** ([2197](https://github.com/puppetlabs/bolt/issue/2197))

  Previously, if a YAML plan had a syntax error Bolt would stacktrace
  due to an assumption about what methods the resulting error had. It now
  fails gracefully with the line of the error.

### CODE REVIEW

File: lib/bolt/pal.rb [hunk 1]
```diff
@@ -29,15 +29,12 @@ def self.from_error(err)
...
-                      column: err.pos }.compact
-                  else
-                    {}
-                  end
-
-        e = new(message, details)
+        details = {}
+        details[:file]    = err.file if defined?(err.file)
+        details[:line]    = err.line if defined?(err.line)
+        details[:column]  = err.pos if defined?(err.pos)
```
Comment (beechtom) [inline lib/bolt/pal.rb:35]:
```suggestion
        details[:file]   = err.file if defined?(err.file)
        details[:line]   = err.line if defined?(err.line)
        details[:column] = err.pos if defined?(err.pos)
```

Not sure how rubocop missed this... it usually doesn't like extra spaces around operators. :|

**Review by beechtom — COMMENTED** [review]
Just a nitpick, but otherwise lgtm.

**Review by beechtom — APPROVED** [review]
